
CAMERA_SOURCES = [0]
CAMERA_LABELS = ["Camera 1"]

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 20

DETECT_CLASSES = [1]
CONFIDENCE_THRESH = 0.5

LIVE_GRID_COLS = 2

RECORD_COLS = None
RECORD_ROWS = None

ALERT_COOLDOWN_SECONDS = 30

SNAPSHOT_DIR = "data/snapshots"
RECORDING_DIR = "data/recordings"

LOG_FILE = "surveillance.log"
